### ISSUE TITLE
RuntimeError: No CUDA GPUs are available

### ISSUE THREAD

**Issue by lakshmi-imrsv** [xcfcode/DDAMS#2]
I am trying to replicate this project.However I am facing this run time error No cuda Gpus available.My system has 4 GPU s and still i am getting this error.Can you help me in solving this?

/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch/nn/modules/rnn.py:63: UserWarning: dropout option adds dropout after all but last recurrent layer, so non-zero dropout expects num_layers greater than 1, but got dropout=0.2 and num_layers=1
  "num_layers={}".format(dropout, num_layers))
Traceback (most recent call last):
  File "translate.py", line 57, in <module>
    main(opt)
  File "translate.py", line 19, in main
    translator = build_translator(opt, report_score=True)
  File "/home/user/DDAMS/onmt/translate/translator.py", line 28, in build_translator
    fields, model, model_opt = load_test_model(opt)
  File "/home/user/DDAMS/onmt/model_builder.py", line 110, in load_test_model
    opt.gpu)
  File "/home/user/DDAMS/onmt/model_builder.py", line 255, in build_base_model
    model.to(device)
  File "/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch/nn/modules/module.py", line 673, in to
    return self._apply(convert)
  File "/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch/nn/modules/module.py", line 409, in _apply
    param_applied = fn(param)
  File "/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch/nn/modules/module.py", line 671, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
  File "/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch/cuda/__init__.py", line 170, in _lazy_init
    torch._C._cuda_init()
RuntimeError: No CUDA GPUs are available

**Comment by xcfcode** [comment]
could you please show your running cmd?

**Comment by lakshmi-imrsv** [comment]
> could you please show your running cmd?

I think I made mistake in  CUDA_VISIBLE_DEVICE=X.When I changed x to 3 (as I have 4 GPUs) I could remove this error.But I am facing a new error now 
ModuleNotFoundError: No module named 'torch_scatter.scatter_cuda'
I had encountered some problems with the module versions while installing requirements.txt. These are the ones which i have installed:
six                   1.15.0
torch                 1.8.1
torch-cluster         1.4.4
torch-geometric       1.3.2
torch-scatter         1.3.1
torch-sparse          0.4.0
torchaudio            0.8.0a0+e4e171a
torchtext             0.4.0
torchvision           0.9.1
tqdm                  4.30.0
Pillow                8.2.0
pyonmttok             1.26.0
pyrouge               0.1.3
PyYAML                5.1.2
future                0.18.2
ConfigArgParse        1.4.1

Do I need to have cuda toolkit also installed?

**Comment by xcfcode** [comment]
Yeah, you should set up your _CUDA env_ correctly, then the `torch_scatter` will include `scatter_cuda` module. When I am preparing this repo, I re-create a new environment, I face the same error.

**Comment by xcfcode** [comment]
It should includes all following files under the pkg dir:`add.py  div.py  __init__.py  max.py  mean.py  min.py  mul.py  __pycache__  **scatter_cpu.cpython-37m-x86_64-linux-gnu.so**  **scatter_cuda.cpython-37m-x86_64-linux-gnu.so**  std.py  sub.py  utils`

**Comment by lakshmi-imrsv** [comment]
I have installed cuda tool kit and re installed torch_scatter.I think that fixed it.However finding errors here
 File "/home/user/anaconda3/envs/ddams/lib/python3.7/site-packages/torch_sparse/__init__.py", line 15, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
AttributeError: 'NoneType' object has no attribute 'origin'
Can you specify the versions of each modules you installed when you re created the new environment?

**Comment by lakshmi-imrsv** [comment]
I have installed cuda tool kit and re installed torch_scatter.I think that fixed it.Now I am able to run the command  and replicate the results.
